py_test(
    name = "tests",
    srcs = ["tests.py"],
    main = "tests.py",
    deps = [
        "//psi_cardinality/python:psi_cardinality"
    ],
    legacy_create_init = False,
    python_version = "PY3",
)
py_test(
    name = "benchmarks",
    srcs = ["benchmarks.py"],
    main = "benchmarks.py",
    deps = [
        "//psi_cardinality/python:psi_cardinality"
    ],
    legacy_create_init = False,
    python_version = "PY3",
)
