py_test(
    name = "test_client",
    srcs = ["test_client.py"],
    main = "test_client.py",
    deps = [
        "//psi_cardinality/python:psi_cardinality"
    ],
    legacy_create_init = False,
    python_version = "PY3",
)
