echo on

bazel test --test_output=all --test_timeout=900 --incompatible_require_linker_input_cc_api=false --features=-supports_dynamic_linker //private_set_intersection/cpp/...
bazel test --test_output=all --test_timeout=900 --incompatible_require_linker_input_cc_api=false --features=-supports_dynamic_linker //private_set_intersection/c/...
